### ISSUE TITLE
Request: Query examples

### ISSUE THREAD

**Issue by pmatos** [jeapostrophe/mongodb#6]
Can you please add some query examples of mongo-structs to the documentation? 

For example, if I want to loop over all mongo-structs in my db, how can I do it?

**Comment by jeapostrophe** [comment]
Hi Paulo, maybe I misunderstand the question, but I don't want to have the mongodb interface documentation duplicate anything in the mongodb documentation. But maybe this will help in this case.

```
(define-mongo-struct cons "cons"
  ([car]
  [cdr]))
(define x (make-cons #:car 1 #:cdr 2))
(define y (make-cons #:car 1))
(mongo-dict-query "cons" empty)
```

This would evaluate to a list containing `x` and `y`.
