### ISSUE TITLE
Pool connection

### ISSUE THREAD

**Issue by hawkish** [jeapostrophe/mongodb#8]
Great and very useful api if you want to take a closer look at mongodb from a Racket point-of-view. I can't seem to find any pooled connections to mongodb though. Or am I missing something?

**Comment by jeapostrophe** [comment]
I recommend using Racket's general pooling system --- http://docs.racket-lang.org/disposable/Reusing_Disposables_with_Pools.html

But if there's some direct thing in the mongodb API, I'm happy to accept a patch.
